#!/bin/bash

# Author:	Keith Patton 2017
# Brief:	A BASH script to launch a GTK+ prompting to confirm
# 		a reboot to Windows installed on a separate partition

# make sure you have GRUB_DEFAULT=saved in your grub config
# (which is autogenerated, you change this part of it by editing /etc/default/grub).
# sudo update-grub to make the changes active

# Find grub menu entries by
# grep -i "menuentry '" /boot/grub/grub.cfg

zenity --question --text="Reboot to Win7?" --icon-name=windows && sudo grub-reboot 4 && shutdown -r now
